services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: UserTRBD
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: python$_venv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

  fastapi:
    build: .
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://postgres:python$_venv@pg:5432/shop
    command: bash -c "cd fastapi-application && alembic upgrade head && python app.app:app.py"
    volumes:
      - ./fastapi-application:/app/fastapi-application
    ports:
      - "8000:8000"
    depends_on:
      - pg

volumes:
  pgdata: